name: Project deploy staging

on:
  push:
    branches:
      - production
#  pull_request:
#    branches:
#      - main

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Deploy files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./dist"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/ubuntu/hypothesis/hypothesis_frontend/html
          EXCLUDE: ".git, .github"
#          SCRIPT_AFTER: |
#            sudo chown -R ubuntu:www-data /home/ubuntu/hypothesis/hypothesis_frontend/html

      - name: Send Mattermost Success Notification
        if: ${{ success() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.NOTIFY_WEBHOOK }}
          json: '{"text": ":white_check_mark: [Annotation project] Staging has been deployed!", "username": "Deploy", "icon_url": "https://avatars.githubusercontent.com/u/8882318?s=200&v=4"}'

      - name: Send Mattermost Failure Notification
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.NOTIFY_WEBHOOK }}
          json: '{"text": ":exclamation: [Annotation project] Failed to deploy staging!", "username": "Deploy", "icon_url": "https://avatars.githubusercontent.com/u/8882318?s=200&v=4"}'
