name: Project deploy staging

on:
  push:
    branches:
      - master


# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: staging_environment

jobs:
  building:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Compile assets
        run: |
          cp .env.staging .env
          echo "VITE_GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
          echo "VITE_GOOGLE_DEV_KEY=${{secrets.GOOGLE_DEV_KEY}}" >> .env
          npm run build

      - name: Deploy files
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{secrets.FRONTEND_DIR}}/
          EXCLUDE: ".git, .github"
          SCRIPT_AFTER: |
            find ${{secrets.FRONTEND_DIR}} -type f -exec chmod 644 {} \;
            find ${{secrets.FRONTEND_DIR}} -type d -exec chmod 755 {} \;

      - name: Send Mattermost Success Notification
        if: ${{ success() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.NOTIFY_WEBHOOK }}
          json: '{"text": ":white_check_mark: [Papaya] Staging has been deployed by GitHub user ${{ github.actor }}!\nChanges: ${{ github.event.head_commit.message }}", "username": "XXXX", "icon_url": "https://avatars.githubusercontent.com/u/8882318?s=200&v=4"}'

      - name: Send Mattermost Failure Notification
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.NOTIFY_WEBHOOK }}
          json: '{"text": ":exclamation: [Papaya] Failed to deploy staging!\nUser: ${{ github.actor }}\nChanges: ${{ github.event.head_commit.message }}", "username": "XXXX", "icon_url": "https://avatars.githubusercontent.com/u/8882318?s=200&v=4"}'
